# Generated by Django 4.1.7 on 2023-02-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='CustomUser', ),
    ]
