# Generated by Django 4.1.7 on 2023-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('CSFs', models.JSONField(default=dict)),
                ('currentMetric', models.JSONField(default=dict)),
                ('metricHistory', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('members', models.JSONField(default=dict)),
            ],
        ),
    ]
