# Generated by Django 4.1.7 on 2023-02-26 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
