# Generated by Django 4.1.7 on 2023-02-28 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard",
         "0003_project_remove_post_author_remove_post_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-StartingDate", )},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="content",
            new_name="Description",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="title",
            new_name="Name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created",
        ),
        migrations.AddField(
            model_name="project",
            name="Budget",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="Completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="Deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="PMembers_size",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="StartingDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
