# Generated by Django 4.1.7 on 2023-02-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_project_budget"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="Budget",),
    ]
