# Generated by Django 4.1.7 on 2023-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_project_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Budget",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
